version: '3.8'

services:

  postgres_container:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    networks:
      - projektchmury-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend-container:
    build: ./backend
    ports:
      - "8081:8080"
    depends_on:
      - postgres_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - projektchmury-network
    container_name: backend_container

  frontend-container:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - projektchmury-network
    container_name: frontend_container
networks:
  projektchmury-network:
    driver: bridge

volumes:
  postgres-data:
